# Plotting a graph over time of the affilitions

In [2]:
import pandas as pd
import numpy as np
All_Data = pd.read_excel('/Users/MattJohnson/Desktop/Affiliations/5. Final consolidation of all data/5.A. Data created in 5./5.2./Final affiliations.xlsx') 
print(All_Data.shape)

(22790, 40)

In [3]:
All_Data.rename(columns = {'Year':'year'}, inplace = True)

melted_master_condenced = All_Data[['Authors_count','year']]

In [4]:
melted_master_condenced['decade'] = ''
melted_master_condenced['decade'] = np.where((melted_master_condenced['year'] >= 1940) & (melted_master_condenced['year'] < 1950), '[1940,1949]', melted_master_condenced['decade'])
melted_master_condenced['decade'] = np.where((melted_master_condenced['year'] >= 1950) & (melted_master_condenced['year'] < 1960), '[1950,1959]', melted_master_condenced['decade'])
melted_master_condenced['decade'] = np.where((melted_master_condenced['year'] >= 1960) & (melted_master_condenced['year'] < 1970), '[1960,1969]', melted_master_condenced['decade'])
melted_master_condenced['decade'] = np.where((melted_master_condenced['year'] >= 1970) & (melted_master_condenced['year'] < 1980), '[1970,1979]', melted_master_condenced['decade'])
melted_master_condenced['decade'] = np.where((melted_master_condenced['year'] >= 1980) & (melted_master_condenced['year'] < 1990), '[1980,1989]', melted_master_condenced['decade'])
melted_master_condenced['decade'] = np.where((melted_master_condenced['year'] >= 1990) & (melted_master_condenced['year'] < 2000), '[1990,1999]', melted_master_condenced['decade'])
melted_master_condenced['decade'] = np.where((melted_master_condenced['year'] >= 2000) & (melted_master_condenced['year'] < 2011), '[2000,2010]', melted_master_condenced['decade'])
print(melted_master_condenced.head())
print(melted_master_condenced.tail())

   Authors_count  year       decade
0            1.0  1940  [1940,1949]
1            1.0  1940  [1940,1949]
2            1.0  1940  [1940,1949]
3            1.0  1940  [1940,1949]
4            1.0  1940  [1940,1949]
       Authors_count  year       decade
22785            1.0  1940  [1940,1949]
22786            1.0  1940  [1940,1949]
22787            1.0  1940  [1940,1949]
22788            1.0  1940  [1940,1949]
22789            1.0  1940  [1940,1949]

/var/folders/23/ft9qf9c11rj_vqhbjml910f40000gn/T/ipykernel_17240/3615562485.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  melted_master_condenced['decade'] = ''
/var/folders/23/ft9qf9c11rj_vqhbjml910f40000gn/T/ipykernel_17240/3615562485.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  melted_master_condenced['decade'] = np.where((melted_master_condenced['year'] >= 1940) & (melted_master_condenced['year'] < 1950), '[1940,1949]', melted_master_condenced['decade'])
/var/folders/23/ft9qf9c11rj_vqhbjml910f40000gn/T/ipykernel_17240/3615562485.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  melted_master_condenced['decade'] = np.where((melted_master_condenced['year'] >= 1950) & (melted_master_condenced['year'] < 1960), '[1950,1959]', melted_master_condenced['decade'])
/var/folders/23/ft9qf9c11rj_vqhbjml910f40000gn/T/ipykernel_17240/3615562485.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  melted_master_condenced['decade'] = np.where((melted_master_condenced['year'] >= 1960) & (melted_master_condenced['year'] < 1970), '[1960,1969]', melted_master_condenced['decade'])
/var/folders/23/ft9qf9c11rj_vqhbjml910f40000gn/T/ipykernel_17240/3615562485.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  melted_master_condenced['decade'] = np.where((melted_master_condenced['year'] >= 1970) & (melted_master_condenced['year'] < 1980), '[1970,1979]', melted_master_condenced['decade'])
/var/folders/23/ft9qf9c11rj_vqhbjml910f40000gn/T/ipykernel_17240/3615562485.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  melted_master_condenced['decade'] = np.where((melted_master_condenced['year'] >= 1980) & (melted_master_condenced['year'] < 1990), '[1980,1989]', melted_master_condenced['decade'])
/var/folders/23/ft9qf9c11rj_vqhbjml910f40000gn/T/ipykernel_17240/3615562485.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  melted_master_condenced['decade'] = np.where((melted_master_condenced['year'] >= 1990) & (melted_master_condenced['year'] < 2000), '[1990,1999]', melted_master_condenced['decade'])
/var/folders/23/ft9qf9c11rj_vqhbjml910f40000gn/T/ipykernel_17240/3615562485.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  melted_master_condenced['decade'] = np.where((melted_master_condenced['year'] >= 2000) & (melted_master_condenced['year'] < 2011), '[2000,2010]', melted_master_condenced['decade'])

In [5]:
melted_master_condenced['sum authors'] = melted_master_condenced.groupby(['decade'])['Authors_count'].cumsum()
melted_master_condenced['count'] = 1
melted_master_condenced['sum papers'] = melted_master_condenced.groupby(['decade'])['count'].cumsum()
melted_master_condenced.head()
a = melted_master_condenced.drop_duplicates(subset = ['decade'], keep = 'last')
a['Average authors'] = a['sum authors']/a['sum papers']
a

/var/folders/23/ft9qf9c11rj_vqhbjml910f40000gn/T/ipykernel_17240/1784397265.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  melted_master_condenced['sum authors'] = melted_master_condenced.groupby(['decade'])['Authors_count'].cumsum()
/var/folders/23/ft9qf9c11rj_vqhbjml910f40000gn/T/ipykernel_17240/1784397265.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  melted_master_condenced['count'] = 1
/var/folders/23/ft9qf9c11rj_vqhbjml910f40000gn/T/ipykernel_17240/1784397265.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  melted_master_condenced['sum papers'] = melted_master_condenced.groupby(['decade'])['count'].cumsum()
/var/folders/23/ft9qf9c11rj_vqhbjml910f40000gn/T/ipykernel_17240/1784397265.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a['Average authors'] = a['sum authors']/a['sum papers']

,Authors_count,year,decade,sum authors,count,sum papers,Average authors
19333,1.0,2000,"[2000,2010]",8037.0,1,4051,1.983955
19898,2.0,1990,"[1990,1999]",6007.0,1,3569,1.683105
20762,1.0,1980,"[1980,1989]",6246.0,1,4234,1.475201
21733,1.0,1970,"[1970,1979]",5681.0,1,4352,1.305377
22241,1.0,1960,"[1960,1969]",3223.0,1,2696,1.195475
22554,1.0,1950,"[1950,1959]",2232.0,1,1981,1.126704
22789,1.0,1940,"[1940,1949]",2171.0,1,1907,1.138437

In [37]:
Data = All_Data.copy()
Data['Same University'] = 0
Data['Same University'] = Data['Same University'].where(Data['0_Auth_affs_0'] != Data['1_Auth_affs_0'], 1)
Data['Same University'] = Data['Same University'].where(Data['0_Auth_affs_0'] != Data['1_Auth_affs_1'], 1)
Data['Same University'] = Data['Same University'].where(Data['0_Auth_affs_0'] != Data['1_Auth_affs_2'], 1)
Data['Same University'] = Data['Same University'].where(Data['0_Auth_affs_0'] != Data['1_Auth_affs_3'], 1)
Data['Same University'] = Data['Same University'].where(Data['0_Auth_affs_0'] != Data['1_Auth_affs_4'], 1)

Data['Same University'] = Data['Same University'].where(Data['0_Auth_affs_1'] != Data['1_Auth_affs_0'], 1)
Data['Same University'] = Data['Same University'].where(Data['0_Auth_affs_1'] != Data['1_Auth_affs_1'], 1)
Data['Same University'] = Data['Same University'].where(Data['0_Auth_affs_1'] != Data['1_Auth_affs_2'], 1)
Data['Same University'] = Data['Same University'].where(Data['0_Auth_affs_1'] != Data['1_Auth_affs_3'], 1)
Data['Same University'] = Data['Same University'].where(Data['0_Auth_affs_1'] != Data['1_Auth_affs_4'], 1)

Data['Same University'] = Data['Same University'].where(Data['0_Auth_affs_2'] != Data['1_Auth_affs_0'], 1)
Data['Same University'] = Data['Same University'].where(Data['0_Auth_affs_2'] != Data['1_Auth_affs_1'], 1)
Data['Same University'] = Data['Same University'].where(Data['0_Auth_affs_2'] != Data['1_Auth_affs_2'], 1)
Data['Same University'] = Data['Same University'].where(Data['0_Auth_affs_2'] != Data['1_Auth_affs_3'], 1)
Data['Same University'] = Data['Same University'].where(Data['0_Auth_affs_2'] != Data['1_Auth_affs_4'], 1)

Data['Same University'] = Data['Same University'].where(Data['0_Auth_affs_3'] != Data['1_Auth_affs_0'], 1)
Data['Same University'] = Data['Same University'].where(Data['0_Auth_affs_3'] != Data['1_Auth_affs_1'], 1)
Data['Same University'] = Data['Same University'].where(Data['0_Auth_affs_3'] != Data['1_Auth_affs_2'], 1)
Data['Same University'] = Data['Same University'].where(Data['0_Auth_affs_3'] != Data['1_Auth_affs_3'], 1)
Data['Same University'] = Data['Same University'].where(Data['0_Auth_affs_3'] != Data['1_Auth_affs_4'], 1)

Data['Same University'] = Data['Same University'].where(Data['0_Auth_affs_4'] != Data['1_Auth_affs_0'], 1)
Data['Same University'] = Data['Same University'].where(Data['0_Auth_affs_4'] != Data['1_Auth_affs_1'], 1)
Data['Same University'] = Data['Same University'].where(Data['0_Auth_affs_4'] != Data['1_Auth_affs_2'], 1)
Data['Same University'] = Data['Same University'].where(Data['0_Auth_affs_4'] != Data['1_Auth_affs_3'], 1)
Data['Same University'] = Data['Same University'].where(Data['0_Auth_affs_4'] != Data['1_Auth_affs_4'], 1)

Data['Same University'] = Data['Same University'].where(Data['1_Auth_affs_0'] != Data['2_Auth_affs_0'], 1)
Data['Same University'] = Data['Same University'].where(Data['1_Auth_affs_0'] != Data['2_Auth_affs_1'], 1)
Data['Same University'] = Data['Same University'].where(Data['1_Auth_affs_0'] != Data['2_Auth_affs_2'], 1)
Data['Same University'] = Data['Same University'].where(Data['1_Auth_affs_0'] != Data['2_Auth_affs_3'], 1)
Data['Same University'] = Data['Same University'].where(Data['1_Auth_affs_0'] != Data['2_Auth_affs_4'], 1)

Data['Same University'] = Data['Same University'].where(Data['1_Auth_affs_1'] != Data['2_Auth_affs_0'], 1)
Data['Same University'] = Data['Same University'].where(Data['1_Auth_affs_1'] != Data['2_Auth_affs_1'], 1)
Data['Same University'] = Data['Same University'].where(Data['1_Auth_affs_1'] != Data['2_Auth_affs_2'], 1)
Data['Same University'] = Data['Same University'].where(Data['1_Auth_affs_1'] != Data['2_Auth_affs_3'], 1)
Data['Same University'] = Data['Same University'].where(Data['1_Auth_affs_1'] != Data['2_Auth_affs_4'], 1)

Data['Same University'] = Data['Same University'].where(Data['1_Auth_affs_2'] != Data['2_Auth_affs_0'], 1)
Data['Same University'] = Data['Same University'].where(Data['1_Auth_affs_2'] != Data['2_Auth_affs_1'], 1)
Data['Same University'] = Data['Same University'].where(Data['1_Auth_affs_2'] != Data['2_Auth_affs_2'], 1)
Data['Same University'] = Data['Same University'].where(Data['1_Auth_affs_2'] != Data['1_Auth_affs_3'], 1)
Data['Same University'] = Data['Same University'].where(Data['1_Auth_affs_2'] != Data['1_Auth_affs_4'], 1)

Data['Same University'] = Data['Same University'].where(Data['1_Auth_affs_3'] != Data['2_Auth_affs_0'], 1)
Data['Same University'] = Data['Same University'].where(Data['1_Auth_affs_3'] != Data['2_Auth_affs_1'], 1)
Data['Same University'] = Data['Same University'].where(Data['1_Auth_affs_3'] != Data['2_Auth_affs_2'], 1)
Data['Same University'] = Data['Same University'].where(Data['1_Auth_affs_3'] != Data['2_Auth_affs_3'], 1)
Data['Same University'] = Data['Same University'].where(Data['1_Auth_affs_3'] != Data['2_Auth_affs_4'], 1)

Data['Same University'] = Data['Same University'].where(Data['1_Auth_affs_4'] != Data['2_Auth_affs_0'], 1)
Data['Same University'] = Data['Same University'].where(Data['1_Auth_affs_4'] != Data['2_Auth_affs_1'], 1)
Data['Same University'] = Data['Same University'].where(Data['1_Auth_affs_4'] != Data['2_Auth_affs_2'], 1)
Data['Same University'] = Data['Same University'].where(Data['1_Auth_affs_4'] != Data['2_Auth_affs_3'], 1)
Data['Same University'] = Data['Same University'].where(Data['1_Auth_affs_4'] != Data['2_Auth_affs_4'], 1)

In [50]:
Data['Diff University'] = 0
Data['Diff University'] = Data['Diff University'].where(Data['0_Auth_affs_0'] == Data['1_Auth_affs_0'], 1)
Data['Diff University'] = Data['Diff University'].where(Data['0_Auth_affs_0'] == Data['1_Auth_affs_1'], 1)
Data['Diff University'] = Data['Diff University'].where(Data['0_Auth_affs_0'] == Data['1_Auth_affs_2'], 1)
Data['Diff University'] = Data['Diff University'].where(Data['0_Auth_affs_0'] == Data['1_Auth_affs_3'], 1)
Data['Diff University'] = Data['Diff University'].where(Data['0_Auth_affs_0'] == Data['1_Auth_affs_4'], 1)

Data['Diff University'] = Data['Diff University'].where(Data['0_Auth_affs_1'] == Data['1_Auth_affs_0'], 1)
Data['Diff University'] = Data['Diff University'].where(Data['0_Auth_affs_1'] == Data['1_Auth_affs_1'], 1)
Data['Diff University'] = Data['Diff University'].where(Data['0_Auth_affs_1'] == Data['1_Auth_affs_2'], 1)
Data['Diff University'] = Data['Diff University'].where(Data['0_Auth_affs_1'] == Data['1_Auth_affs_3'], 1)
Data['Diff University'] = Data['Diff University'].where(Data['0_Auth_affs_1'] == Data['1_Auth_affs_4'], 1)

Data['Diff University'] = Data['Diff University'].where(Data['0_Auth_affs_2'] == Data['1_Auth_affs_0'], 1)
Data['Diff University'] = Data['Diff University'].where(Data['0_Auth_affs_2'] == Data['1_Auth_affs_1'], 1)
Data['Diff University'] = Data['Diff University'].where(Data['0_Auth_affs_2'] == Data['1_Auth_affs_2'], 1)
Data['Diff University'] = Data['Diff University'].where(Data['0_Auth_affs_2'] == Data['1_Auth_affs_3'], 1)
Data['Diff University'] = Data['Diff University'].where(Data['0_Auth_affs_2'] == Data['1_Auth_affs_4'], 1)

Data['Diff University'] = Data['Diff University'].where(Data['0_Auth_affs_3'] == Data['1_Auth_affs_0'], 1)
Data['Diff University'] = Data['Diff University'].where(Data['0_Auth_affs_3'] == Data['1_Auth_affs_1'], 1)
Data['Diff University'] = Data['Diff University'].where(Data['0_Auth_affs_3'] == Data['1_Auth_affs_2'], 1)
Data['Diff University'] = Data['Diff University'].where(Data['0_Auth_affs_3'] == Data['1_Auth_affs_3'], 1)
Data['Diff University'] = Data['Diff University'].where(Data['0_Auth_affs_3'] == Data['1_Auth_affs_4'], 1)

Data['Diff University'] = Data['Diff University'].where(Data['0_Auth_affs_4'] == Data['1_Auth_affs_0'], 1)
Data['Diff University'] = Data['Diff University'].where(Data['0_Auth_affs_4'] == Data['1_Auth_affs_1'], 1)
Data['Diff University'] = Data['Diff University'].where(Data['0_Auth_affs_4'] == Data['1_Auth_affs_2'], 1)
Data['Diff University'] = Data['Diff University'].where(Data['0_Auth_affs_4'] == Data['1_Auth_affs_3'], 1)
Data['Diff University'] = Data['Diff University'].where(Data['0_Auth_affs_4'] == Data['1_Auth_affs_4'], 1)

Data['Diff University'] = Data['Diff University'].where(Data['1_Auth_affs_0'] == Data['2_Auth_affs_0'], 1)
Data['Diff University'] = Data['Diff University'].where(Data['1_Auth_affs_0'] == Data['2_Auth_affs_1'], 1)
Data['Diff University'] = Data['Diff University'].where(Data['1_Auth_affs_0'] == Data['2_Auth_affs_2'], 1)
Data['Diff University'] = Data['Diff University'].where(Data['1_Auth_affs_0'] == Data['2_Auth_affs_3'], 1)
Data['Diff University'] = Data['Diff University'].where(Data['1_Auth_affs_0'] == Data['2_Auth_affs_4'], 1)

Data['Diff University'] = Data['Diff University'].where(Data['1_Auth_affs_1'] == Data['2_Auth_affs_0'], 1)
Data['Diff University'] = Data['Diff University'].where(Data['1_Auth_affs_1'] == Data['2_Auth_affs_1'], 1)
Data['Diff University'] = Data['Diff University'].where(Data['1_Auth_affs_1'] == Data['2_Auth_affs_2'], 1)
Data['Diff University'] = Data['Diff University'].where(Data['1_Auth_affs_1'] == Data['2_Auth_affs_3'], 1)
Data['Diff University'] = Data['Diff University'].where(Data['1_Auth_affs_1'] == Data['2_Auth_affs_4'], 1)

Data['Diff University'] = Data['Diff University'].where(Data['1_Auth_affs_2'] == Data['2_Auth_affs_0'], 1)
Data['Diff University'] = Data['Diff University'].where(Data['1_Auth_affs_2'] == Data['2_Auth_affs_1'], 1)
Data['Diff University'] = Data['Diff University'].where(Data['1_Auth_affs_2'] == Data['2_Auth_affs_2'], 1)
Data['Diff University'] = Data['Diff University'].where(Data['1_Auth_affs_2'] == Data['1_Auth_affs_3'], 1)
Data['Diff University'] = Data['Diff University'].where(Data['1_Auth_affs_2'] == Data['1_Auth_affs_4'], 1)

Data['Diff University'] = Data['Diff University'].where(Data['1_Auth_affs_3'] == Data['2_Auth_affs_0'], 1)
Data['Diff University'] = Data['Diff University'].where(Data['1_Auth_affs_3'] == Data['2_Auth_affs_1'], 1)
Data['Diff University'] = Data['Diff University'].where(Data['1_Auth_affs_3'] == Data['2_Auth_affs_2'], 1)
Data['Diff University'] = Data['Diff University'].where(Data['1_Auth_affs_3'] == Data['2_Auth_affs_3'], 1)
Data['Diff University'] = Data['Diff University'].where(Data['1_Auth_affs_3'] == Data['2_Auth_affs_4'], 1)

Data['Diff University'] = Data['Diff University'].where(Data['1_Auth_affs_4'] == Data['2_Auth_affs_0'], 1)
Data['Diff University'] = Data['Diff University'].where(Data['1_Auth_affs_4'] == Data['2_Auth_affs_1'], 1)
Data['Diff University'] = Data['Diff University'].where(Data['1_Auth_affs_4'] == Data['2_Auth_affs_2'], 1)
Data['Diff University'] = Data['Diff University'].where(Data['1_Auth_affs_4'] == Data['2_Auth_affs_3'], 1)
Data['Diff University'] = Data['Diff University'].where(Data['1_Auth_affs_4'] == Data['2_Auth_affs_4'], 1)

In [58]:
melted_master_condenced = Data[['year','Authors_count','Same University','Diff University']]
print(melted_master_condenced.head())

melted_master_condenced['decade'] = ''
melted_master_condenced['decade'] = np.where((melted_master_condenced['year'] >= 1940) & (melted_master_condenced['year'] < 1950), '[1940,1949]', melted_master_condenced['decade'])
melted_master_condenced['decade'] = np.where((melted_master_condenced['year'] >= 1950) & (melted_master_condenced['year'] < 1960), '[1950,1959]', melted_master_condenced['decade'])
melted_master_condenced['decade'] = np.where((melted_master_condenced['year'] >= 1960) & (melted_master_condenced['year'] < 1970), '[1960,1969]', melted_master_condenced['decade'])
melted_master_condenced['decade'] = np.where((melted_master_condenced['year'] >= 1970) & (melted_master_condenced['year'] < 1980), '[1970,1979]', melted_master_condenced['decade'])
melted_master_condenced['decade'] = np.where((melted_master_condenced['year'] >= 1980) & (melted_master_condenced['year'] < 1990), '[1980,1989]', melted_master_condenced['decade'])
melted_master_condenced['decade'] = np.where((melted_master_condenced['year'] >= 1990) & (melted_master_condenced['year'] < 2000), '[1990,1999]', melted_master_condenced['decade'])
melted_master_condenced['decade'] = np.where((melted_master_condenced['year'] >= 2000) & (melted_master_condenced['year'] < 2011), '[2000,2010]', melted_master_condenced['decade'])

#melted_master_condenced['aff_cum_counts'] = melted_master_condenced.groupby(['decade'])['Same University'].cumcount()+1
melted_master_condenced['Same University'] = melted_master_condenced['Same University'].astype(int)
melted_master_condenced['sum same university'] = melted_master_condenced.groupby(['decade','Authors_count'])['Same University'].cumsum()
#melted_master_condenced['sum diff university'] = melted_master_condenced.groupby(['decade','Authors_count'])['Diff University'].cumsum()
melted_master_condenced['count'] = 1
melted_master_condenced['sum papers'] = melted_master_condenced.groupby(['decade','Authors_count'])['count'].cumsum()

melted_master_condenced['sum diff university'] = np.where(melted_master_condenced['Authors_count'] > 1, melted_master_condenced['sum papers'] - melted_master_condenced['sum same university'] , 0)

a = melted_master_condenced.drop_duplicates(subset = ['decade','Authors_count'], keep = 'last')
mask_journal = a['Authors_count'].isin([2,3,4,5])
a = a[mask_journal]
#a['Average authors'] = a['sum authors']/a['sum papers']
a

   year  Authors_count  Same University  Diff University
0  1940            1.0                0                1
1  1940            1.0                0                1
2  1940            1.0                0                1
3  1940            1.0                0                1
4  1940            1.0                0                1

/var/folders/23/ft9qf9c11rj_vqhbjml910f40000gn/T/ipykernel_17240/796660524.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  melted_master_condenced['decade'] = ''
/var/folders/23/ft9qf9c11rj_vqhbjml910f40000gn/T/ipykernel_17240/796660524.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  melted_master_condenced['decade'] = np.where((melted_master_condenced['year'] >= 1940) & (melted_master_condenced['year'] < 1950), '[1940,1949]', melted_master_condenced['decade'])
/var/folders/23/ft9qf9c11rj_vqhbjml910f40000gn/T/ipykernel_17240/796660524.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  melted_master_condenced['decade'] = np.where((melted_master_condenced['year'] >= 1950) & (melted_master_condenced['year'] < 1960), '[1950,1959]', melted_master_condenced['decade'])
/var/folders/23/ft9qf9c11rj_vqhbjml910f40000gn/T/ipykernel_17240/796660524.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  melted_master_condenced['decade'] = np.where((melted_master_condenced['year'] >= 1960) & (melted_master_condenced['year'] < 1970), '[1960,1969]', melted_master_condenced['decade'])
/var/folders/23/ft9qf9c11rj_vqhbjml910f40000gn/T/ipykernel_17240/796660524.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  melted_master_condenced['decade'] = np.where((melted_master_condenced['year'] >= 1970) & (melted_master_condenced['year'] < 1980), '[1970,1979]', melted_master_condenced['decade'])
/var/folders/23/ft9qf9c11rj_vqhbjml910f40000gn/T/ipykernel_17240/796660524.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  melted_master_condenced['decade'] = np.where((melted_master_condenced['year'] >= 1980) & (melted_master_condenced['year'] < 1990), '[1980,1989]', melted_master_condenced['decade'])
/var/folders/23/ft9qf9c11rj_vqhbjml910f40000gn/T/ipykernel_17240/796660524.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  melted_master_condenced['decade'] = np.where((melted_master_condenced['year'] >= 1990) & (melted_master_condenced['year'] < 2000), '[1990,1999]', melted_master_condenced['decade'])
/var/folders/23/ft9qf9c11rj_vqhbjml910f40000gn/T/ipykernel_17240/796660524.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  melted_master_condenced['decade'] = np.where((melted_master_condenced['year'] >= 2000) & (melted_master_condenced['year'] < 2011), '[2000,2010]', melted_master_condenced['decade'])
/var/folders/23/ft9qf9c11rj_vqhbjml910f40000gn/T/ipykernel_17240/796660524.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  melted_master_condenced['Same University'] = melted_master_condenced['Same University'].astype(int)
/var/folders/23/ft9qf9c11rj_vqhbjml910f40000gn/T/ipykernel_17240/796660524.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  melted_master_condenced['sum same university'] = melted_master_condenced.groupby(['decade','Authors_count'])['Same University'].cumsum()
/var/folders/23/ft9qf9c11rj_vqhbjml910f40000gn/T/ipykernel_17240/796660524.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  melted_master_condenced['count'] = 1
/var/folders/23/ft9qf9c11rj_vqhbjml910f40000gn/T/ipykernel_17240/796660524.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  melted_master_condenced['sum papers'] = melted_master_condenced.groupby(['decade','Authors_count'])['count'].cumsum()
/var/folders/23/ft9qf9c11rj_vqhbjml910f40000gn/T/ipykernel_17240/796660524.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  melted_master_condenced['sum diff university'] = np.where(melted_master_condenced['Authors_count'] > 1, melted_master_condenced['sum papers'] - melted_master_condenced['sum same university'] , 0)

,year,Authors_count,Same University,Diff University,decade,sum same university,count,sum papers,sum diff university
3950,1977,5.0,0,1,"[1970,1979]",0,1,1,1
11130,2001,5.0,0,1,"[2000,2010]",8,1,30,22
14556,1980,5.0,0,1,"[1980,1989]",3,1,4,1
16151,1969,5.0,0,1,"[1960,1969]",0,1,1,1
17508,1953,4.0,0,1,"[1950,1959]",0,1,4,4
17709,1950,5.0,0,1,"[1950,1959]",0,1,1,1
18650,1940,4.0,0,1,"[1940,1949]",0,1,2,2
18652,1940,5.0,1,1,"[1940,1949]",2,1,6,4
19316,2000,4.0,0,1,"[2000,2010]",61,1,135,74
19326,2000,3.0,0,1,"[2000,2010]",360,1,775,415
19332,2000,2.0,1,1,"[2000,2010]",607,1,1900,1293
19854,1990,4.0,0,1,"[1990,1999]",32,1,63,31
19856,1990,5.0,0,1,"[1990,1999]",4,1,6,2
19896,1990,3.0,0,1,"[1990,1999]",166,1,356,190
19898,1990,2.0,1,1,"[1990,1999]",536,1,1503,967
20711,1980,4.0,1,1,"[1980,1989]",14,1,26,12
20756,1980,3.0,1,1,"[1980,1989]",134,1,255,121
20760,1980,2.0,1,1,"[1980,1989]",598,1,1410,812
21691,1970,4.0,0,1,"[1970,1979]",6,1,13,7
21701,1970,3.0,0,1,"[1970,1979]",84,1,136,52
21722,1970,2.0,1,1,"[1970,1979]",481,1,1019,538
22110,1962,4.0,1,1,"[1960,1969]",4,1,5,1
22188,1960,3.0,1,1,"[1960,1969]",22,1,41,19
22234,1960,2.0,1,1,"[1960,1969]",230,1,428,198
22477,1952,2.0,0,1,"[1950,1959]",96,1,146,50
22531,1950,3.0,1,1,"[1950,1959]",17,1,22,5
22557,1949,3.0,0,1,"[1940,1949]",5,1,8,3
22782,1940,2.0,1,1,"[1940,1949]",77,1,100,23

In [62]:
melted_master_condenced = Data[['year','Authors_count','Same University','Diff University']]
print(melted_master_condenced.head())

melted_master_condenced['decade'] = ''
melted_master_condenced['decade'] = np.where((melted_master_condenced['year'] >= 1940) & (melted_master_condenced['year'] < 1950), '[1940,1949]', melted_master_condenced['decade'])
melted_master_condenced['decade'] = np.where((melted_master_condenced['year'] >= 1950) & (melted_master_condenced['year'] < 1960), '[1950,1959]', melted_master_condenced['decade'])
melted_master_condenced['decade'] = np.where((melted_master_condenced['year'] >= 1960) & (melted_master_condenced['year'] < 1970), '[1960,1969]', melted_master_condenced['decade'])
melted_master_condenced['decade'] = np.where((melted_master_condenced['year'] >= 1970) & (melted_master_condenced['year'] < 1980), '[1970,1979]', melted_master_condenced['decade'])
melted_master_condenced['decade'] = np.where((melted_master_condenced['year'] >= 1980) & (melted_master_condenced['year'] < 1990), '[1980,1989]', melted_master_condenced['decade'])
melted_master_condenced['decade'] = np.where((melted_master_condenced['year'] >= 1990) & (melted_master_condenced['year'] < 2000), '[1990,1999]', melted_master_condenced['decade'])
melted_master_condenced['decade'] = np.where((melted_master_condenced['year'] >= 2000) & (melted_master_condenced['year'] < 2011), '[2000,2010]', melted_master_condenced['decade'])

#melted_master_condenced['aff_cum_counts'] = melted_master_condenced.groupby(['decade'])['Same University'].cumcount()+1
melted_master_condenced['Same University'] = melted_master_condenced['Same University'].astype(int)
melted_master_condenced['sum same university'] = melted_master_condenced.groupby(['decade'])['Same University'].cumsum()
#melted_master_condenced['sum diff university'] = melted_master_condenced.groupby(['decade','Authors_count'])['Diff University'].cumsum()
melted_master_condenced['count'] = 1

mask_journal = melted_master_condenced['Authors_count'].isin([1])
melted_master_condenced = melted_master_condenced[~mask_journal]
melted_master_condenced['sum papers'] = melted_master_condenced.groupby(['decade'])['count'].cumsum()

melted_master_condenced['sum diff university'] = np.where(melted_master_condenced['Authors_count'] > 1, melted_master_condenced['sum papers'] - melted_master_condenced['sum same university'] , 0)

a = melted_master_condenced.drop_duplicates(subset = ['decade'], keep = 'last')

#a['Average authors'] = a['sum authors']/a['sum papers']
a

   year  Authors_count  Same University  Diff University
0  1940            1.0                0                1
1  1940            1.0                0                1
2  1940            1.0                0                1
3  1940            1.0                0                1
4  1940            1.0                0                1

/var/folders/23/ft9qf9c11rj_vqhbjml910f40000gn/T/ipykernel_17240/1727776855.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  melted_master_condenced['decade'] = ''
/var/folders/23/ft9qf9c11rj_vqhbjml910f40000gn/T/ipykernel_17240/1727776855.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  melted_master_condenced['decade'] = np.where((melted_master_condenced['year'] >= 1940) & (melted_master_condenced['year'] < 1950), '[1940,1949]', melted_master_condenced['decade'])
/var/folders/23/ft9qf9c11rj_vqhbjml910f40000gn/T/ipykernel_17240/1727776855.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  melted_master_condenced['decade'] = np.where((melted_master_condenced['year'] >= 1950) & (melted_master_condenced['year'] < 1960), '[1950,1959]', melted_master_condenced['decade'])
/var/folders/23/ft9qf9c11rj_vqhbjml910f40000gn/T/ipykernel_17240/1727776855.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  melted_master_condenced['decade'] = np.where((melted_master_condenced['year'] >= 1960) & (melted_master_condenced['year'] < 1970), '[1960,1969]', melted_master_condenced['decade'])
/var/folders/23/ft9qf9c11rj_vqhbjml910f40000gn/T/ipykernel_17240/1727776855.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  melted_master_condenced['decade'] = np.where((melted_master_condenced['year'] >= 1970) & (melted_master_condenced['year'] < 1980), '[1970,1979]', melted_master_condenced['decade'])
/var/folders/23/ft9qf9c11rj_vqhbjml910f40000gn/T/ipykernel_17240/1727776855.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  melted_master_condenced['decade'] = np.where((melted_master_condenced['year'] >= 1980) & (melted_master_condenced['year'] < 1990), '[1980,1989]', melted_master_condenced['decade'])
/var/folders/23/ft9qf9c11rj_vqhbjml910f40000gn/T/ipykernel_17240/1727776855.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  melted_master_condenced['decade'] = np.where((melted_master_condenced['year'] >= 1990) & (melted_master_condenced['year'] < 2000), '[1990,1999]', melted_master_condenced['decade'])
/var/folders/23/ft9qf9c11rj_vqhbjml910f40000gn/T/ipykernel_17240/1727776855.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  melted_master_condenced['decade'] = np.where((melted_master_condenced['year'] >= 2000) & (melted_master_condenced['year'] < 2011), '[2000,2010]', melted_master_condenced['decade'])
/var/folders/23/ft9qf9c11rj_vqhbjml910f40000gn/T/ipykernel_17240/1727776855.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  melted_master_condenced['Same University'] = melted_master_condenced['Same University'].astype(int)
/var/folders/23/ft9qf9c11rj_vqhbjml910f40000gn/T/ipykernel_17240/1727776855.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  melted_master_condenced['sum same university'] = melted_master_condenced.groupby(['decade'])['Same University'].cumsum()
/var/folders/23/ft9qf9c11rj_vqhbjml910f40000gn/T/ipykernel_17240/1727776855.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  melted_master_condenced['count'] = 1
/var/folders/23/ft9qf9c11rj_vqhbjml910f40000gn/T/ipykernel_17240/1727776855.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  melted_master_condenced['sum papers'] = melted_master_condenced.groupby(['decade'])['count'].cumsum()
/var/folders/23/ft9qf9c11rj_vqhbjml910f40000gn/T/ipykernel_17240/1727776855.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  melted_master_condenced['sum diff university'] = np.where(melted_master_condenced['Authors_count'] > 1, melted_master_condenced['sum papers'] - melted_master_condenced['sum same university'] , 0)

,year,Authors_count,Same University,Diff University,decade,sum same university,count,sum papers,sum diff university
19332,2000,2.0,1,1,"[2000,2010]",1037,1,2848,1811
19898,1990,2.0,1,1,"[1990,1999]",739,1,1932,1193
20760,1980,2.0,1,1,"[1980,1989]",749,1,1697,948
21722,1970,2.0,1,1,"[1970,1979]",571,1,1174,603
22234,1960,2.0,1,1,"[1960,1969]",257,1,484,227
22531,1950,3.0,1,1,"[1950,1959]",113,1,179,66
22782,1940,2.0,1,1,"[1940,1949]",85,1,136,51